root: true
extends: 'eslint:recommended'
rules:
  eol-last: 2
# eqeqeq:                  [ 2, allow-null ]
  eqeqeq:                  [ 1, allow-null ]
  indent:                  [ 2, 2, { SwitchCase: 1 }]
  no-trailing-spaces:      [ 2, { 'skipBlankLines': true, 'ignoreComments': true }]
  no-unused-vars:          [ 2, { vars: all, args: none, ignoreRestSiblings: true }]
# User defined rules
  array-bracket-spacing:   [ 2, 'never' ]
  block-spacing:           [ 2, 'always' ]
  brace-style:             [ 2, '1tbs', { 'allowSingleLine': false }]
  comma-style:             [ 2, 'last' ]
  curly:                   [ 2, 'all' ]
  dot-location:            [ 2, 'property' ]
  linebreak-style:         [ 2, 'windows' ]
  multiline-comment-style: [ 2, 'starred-block' ]
# no-cond-assign:          2
  no-cond-assign:          1
  no-console:              0
  no-control-regex:        0
  no-multiple-empty-lines: [ 2, { 'max': 1, 'maxBOF': 0, 'maxEOF': 1 }]
  no-redeclare:            1
# no-undef:                2
  no-undef:                0
  no-useless-escape:       1
  no-unexpected-multiline: 2
  object-curly-spacing:    [ 2, 'always', { 'objectsInObjects': false }]
  semi:                    [ 2, 'always' ]
  semi-spacing:            [ 2, { 'before': false, 'after': true }]
  space-before-blocks:     [ 2, 'always']
  space-before-function-paren: [ 2, { 'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always' }]
  spaced-comment:          [ 2, 'always']
